### ISSUE TITLE
Running ace in headless mode stopped working in v1.2.8 and 1.3.0

### ISSUE THREAD

**Issue by josteinaj** [daisy/ace#392]
**the version of Ace impacted by the issue (as returned by the `ace -v` command).**

1.2.8, 1.3.0, 1.3.1

**the version of Node used to run Ace (as returned by the `node -v` command).**

v16.19.1

**your operating system and version.**

Linux / Docker

**if the issue is a bug when running Ace: the error message as produced in the log file (you can enable debug logging with the `--verbose` option).**

Version 1.2.8:
```
(…)
Error: Cannot find module 'electron'
(…)
```

Version 1.3.0 and 1.3.1:
```
/usr/local/lib/node_modules/@daisy/ace/node_modules/electron/dist/electron: error while loading shared libraries: libnss3.so: cannot open shared object file: No such file or directory
```

**if possible, let us know if you can share a sample input file to help us reproduce the issue.**

```bash
docker run --rm -it node:16 bash
npm install @daisy/ace@1.3.1 --location=global
ace
```

**Comment by danielweck** [comment]
Hello, Ace with Puppeteer (which is now deprecated but still available when installing Ace) runs without any special configuration in a headless Docker Linux container, but Electron requires xfvb virtual buffer and some configuration.

See the following Dockerfile demonstration:

https://github.com/daisy/ace/blob/master/Dockerfile

To test this, simply place a file named `book.epub` in the directory and call `docker.sh`:

https://github.com/daisy/ace/blob/master/docker.sh

Obviously, this is not ideal and I would like to better understand if the Electron BrowserWindow code which I suspect causes the virtual buffer requirement can be configured to run headless Chromium (assuming this is how Puppeteer gets around this). There is also the "no sandbox" command line argument which can be integrated directly in Javascript when launching the Electron instance (I suspect Puppeteer includes this by default).

**Comment by jenstroeger** [comment]
Thanks @danielweck — turns out that installing the virtual fb https://github.com/daisy/ace/blob/ba239723a3efd301c2bbf875fd9b337476353a69/Dockerfile#L91 and passing the right options worked.

Just out of curiosity regarding how ACE is being run here https://github.com/daisy/ace/blob/ba239723a3efd301c2bbf875fd9b337476353a69/Dockerfile#L103

- Both `--no-sandbox` and `--disable-gpu` seem to be Chromium options ([docs](https://www.chromium.org/developers/how-tos/run-chromium-with-flags/)) — does ACE pass those through? I didn’t see that documented with `--help` or [here](https://daisy.github.io/ace/docs/cli/)?
- Why is running ACE in a virtual X fb necessary, what does ACE do with the rendering? (Sorry, I don’t have the time at the moment to dive into the [code](https://github.com/daisy/ace/tree/master/packages) to figure this out myself 🤓)
- What’s the difference between running `ace` (what I do) and `ace-electron` (in your Dockerfile)?

**Comment by danielweck** [comment]
Hello, 'ace' is synonym with 'ace-electron', and 'ace-puppeteer' is the legacy "runner" for the Deque Axe evaluation engine. Both the Electron and Puppeteer "runners" launch Chromium web browser instances (webviews) to execute the Axe JavaScript, but they do it in slightly different ways. Unfortunately the Electron "runner" is not truly headless, thus the virtual framebuffer hacks. Older versions of Daisy Ace (CLI) used to run Puppeteer by default but this potentially caused discrepancies with the Daisy Ace App (GUI) accessibility reports, due to the application relying on Electron instead of Puppeteer. Daisy Ace (CLI) has since switched to Electron by default, which not only introduced much needed consistency, but also improved evaluation performance (also note that the Chromium version shipped in Ace's current Puppeteer integration is older than the version shipped with Electron). The Puppeteer Ace command line launcher remains available (and requires no virtual framebuffer hack in headless Docker-like containers) but this is not the recommended method, for the reasons previously given. I hope this helps.
